spring.application.name=ServerDrivenUI-Service

#################################################################################################
#                                   Database Configuration
#################################################################################################
# MSSQL Database Configuration (Internal Docker Network)
spring.datasource.url=jdbc:sqlserver://mssql_db:1433;databaseName=server_driven_ui_db;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# Use application user instead of 'sa' for security
spring.datasource.username=server_driven_ui_user
spring.datasource.password=8fd2SSSvf3fp3tL8p!Bkdd!d8GGh#2j8YjS6L#msPnsmLkt2fKwDs58oP3

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# SQL Initialization - Set to 'never' until you fix data.sql (TRUE -> 1)
spring.sql.init.mode=never
spring.sql.init.continue-on-error=false

# Logging
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.dev.codexo=DEBUG