spring.application.name=ServerDrivenUI-Servcie


#################################################################################################
# 										Database Configuration
#################################################################################################
# MSSQL Database Configuration (Internal Docker Network)
# Hostname 'mssql_db' matches the service name in docker-compose
spring.datasource.url=jdbc:sqlserver://mssql_db:1433;databaseName=server_driven_ui_db;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=MSSql@2024!Strong#Pass

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false

# Detailed Logging
logging.level.org.springframework.jdbc.datasource.init=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.dev.codexo=DEBUG